# ~/.config/starship.toml
format = """
$conda\
$username\
$hostname\
$directory\
$git_branch\
$git_status\
$fill\
$cmd_duration\
$line_break\
$character"""

add_newline = true

[conda]
ignore_base = false
style = 'white'
symbol = "\ue73c  "
format = '[\($symbol$environment\)]($style) '

[username]
show_always = true
style_user = 'bold fg:#3ecc71'
format = '[$user]($style)'

[directory]
truncation_length = 8
truncation_symbol = '.../'
truncate_to_repo = false
style = 'bold fg:#3ecc71'
format = ':[$path]($style) '

[python]
format = "via [$symbol$virtualenv]($style)"

[fill]
symbol = ' '

[cmd_duration]
style = "yellow"
format = 'took [$duration]($style) '

[character]
success_symbol = '[\$](bold fg:#2ecc71)'
error_symbol = '[\$](bold red)'
