# ~/.config/starship.toml
format = """
$conda\
$hostname\
$username\
$directory\
$git_branch\
$git_status\
$fill\
$cmd_duration\
$line_break\
$character"""

add_newline = true

[conda]
ignore_base = false
style = "white"
format = "[($environment)]($style) "

[hostname]
format = '[$ssh_symbol]($style)'

[username]
style_user = "bold fg:green"
format = '[$user]($style)'

[directory]
truncation_length = 8
truncation_symbol = ".../"
truncate_to_repo = false
style = "bold fg:green"
format = "[$path]($style) "

[fill]
symbol = " "

[cmd_duration]
style = "yellow"
format = "took [$duration]($style) "
